#!/usr/bin/env bash
# MajNet one-line installer — MAIN node only (ADR 0004, roadmap phase 6):
#
#   curl -fsSL https://raw.githubusercontent.com/maxa-ondrej/majnet/main/bootstrap/install.sh | bash
#
# Bootstraps this node as `main`, builds and installs the control plane
# (bot, reconciler, setup) as systemd services, generates all local key
# material, and prints the setup-wizard URL. Worker nodes are enrolled from
# the wizard — never run this on them. Idempotent; safe to re-run.
#
# Env overrides: MAJNET_REPO_URL, MAJNET_REF, MAJNET_PUBLIC_IP.

set -euo pipefail

REPO_URL=${MAJNET_REPO_URL:-https://github.com/maxa-ondrej/majnet}
REF=${MAJNET_REF:-main}
DIR=/opt/majnet
ETC=/etc/majnet

log() { printf '\033[1;34m[majnet-install]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[majnet-install]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root"
[[ -f /etc/debian_version ]] || die "Debian only (design doc §4)"

log "installing build + runtime dependencies"
apt-get update -q
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  git curl ca-certificates build-essential pkg-config libssl-dev \
  age openssl openssh-client

if ! command -v cargo &>/dev/null && [[ ! -x $HOME/.cargo/bin/cargo ]]; then
  log "installing Rust (rustup, minimal profile)"
  curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
fi
export PATH="$HOME/.cargo/bin:$PATH"

log "fetching $REPO_URL @ $REF → $DIR"
if [[ -d $DIR/.git ]]; then
  git -C "$DIR" fetch --depth 1 origin "$REF"
  git -C "$DIR" checkout -q FETCH_HEAD
else
  git clone --depth 1 --branch "$REF" "$REPO_URL" "$DIR"
fi

mkdir -p "$ETC"

PUBLIC_IP=${MAJNET_PUBLIC_IP:-$(curl -fsS4 --max-time 10 https://ifconfig.me || true)}
[[ -n $PUBLIC_IP ]] || die "could not detect the public IP — set MAJNET_PUBLIC_IP"

# --- node.env (role=main) ------------------------------------------------
# 10-base disables root SSH, so whatever key got the operator in as root
# becomes the admin user's key — no lockout window.
if [[ ! -f $ETC/node.env ]]; then
  log "writing $ETC/node.env (role=main)"
  ADMIN_KEYS=$(grep -hv '^[[:space:]]*$' /root/.ssh/authorized_keys 2>/dev/null || true)
  (umask 077; cat > "$ETC/node.env" <<EOF
# Generated by install.sh — re-rendered by majnet-setup on node enrollment.
NODE_NAME=main
NODE_ROLE=main
WG_ADDRESS=10.88.0.1/24
WG_LISTEN_PORT=51820
WG_PEERS=""
DOCKER_API_PORT=2376
ADMIN_USER=majnet
ADMIN_SSH_KEYS="
$ADMIN_KEYS
"
BESZEL_HUB_URL=http://10.88.0.1:8090
BESZEL_AGENT_KEY=
RESTIC_REPOSITORY=
EOF
  )
fi

# --- key material (before bootstrap: step 30 points dockerd at the certs) -
log "generating key material"
PKI_CA="$ETC/pki-ca"
bash "$DIR/bootstrap/pki/gen-certs.sh" "$PKI_CA" >/dev/null
install -D -m 0600 "$PKI_CA/ca.pem"               "$ETC/pki/ca.pem"
install -D -m 0600 "$PKI_CA/server-main-cert.pem" "$ETC/pki/server-cert.pem"
install -D -m 0600 "$PKI_CA/server-main-key.pem"  "$ETC/pki/server-key.pem"
install -D -m 0600 "$PKI_CA/reconciler-cert.pem"  "$ETC/pki/reconciler-cert.pem"
install -D -m 0600 "$PKI_CA/reconciler-key.pem"   "$ETC/pki/reconciler-key.pem"

install -d -m 0700 "$ETC/age"
[[ -f $ETC/age/age-stable.key     ]] || age-keygen -o "$ETC/age/age-stable.key"     2>/dev/null
[[ -f $ETC/age/age-production.key ]] || age-keygen -o "$ETC/age/age-production.key" 2>/dev/null
[[ -f $ETC/age/db-master.key      ]] || (umask 077; openssl rand -hex 32 > "$ETC/age/db-master.key")

[[ -f $ETC/enroll_ed25519 ]] || ssh-keygen -q -t ed25519 -N '' -C majnet-enroll -f "$ETC/enroll_ed25519"
[[ -f $ETC/setup-token    ]] || (umask 077; openssl rand -hex 24 > "$ETC/setup-token")

# --- bootstrap this node ---------------------------------------------------
log "bootstrapping node 'main' (WireGuard, Docker, firewall)"
bash "$DIR/bootstrap/bootstrap.sh"

# --- build + install the control plane -------------------------------------
log "building the control plane (release — several minutes on a small VPS)"
(cd "$DIR" && cargo build --release -p majnet-bot -p majnet-reconciler -p majnet-setup)
install -m 0755 "$DIR/target/release/majnet-bot"        /usr/local/bin/
install -m 0755 "$DIR/target/release/majnet-reconciler" /usr/local/bin/
install -m 0755 "$DIR/target/release/majnet-setup"      /usr/local/bin/

# --- service config + units ------------------------------------------------
# bot.env is written by the wizard (App credentials); reconciler + setup are
# fully known now.
(umask 077; cat > "$ETC/reconciler.env" <<'EOF'
MAJNET_BOT_URL=http://10.88.0.1:8081
MAJNET_LISTEN=10.88.0.1:9090
MAJNET_ROOT_ORG=majksa-platform
MAJNET_AGE_KEY_DIR=/etc/majnet/age
MAJNET_DOCKER_CERT_DIR=/etc/majnet/pki
MAJNET_DATA_DIR=/var/lib/majnet-reconciler
EOF
)
(umask 077; cat > "$ETC/setup.env" <<'EOF'
MAJNET_SETUP_LISTEN_PUBLIC=0.0.0.0:7600
MAJNET_SETUP_LISTEN_INTERNAL=10.88.0.1:7601
MAJNET_BOT_INTERNAL_URL=http://10.88.0.1:8081
MAJNET_ETC_DIR=/etc/majnet
MAJNET_REPO_DIR=/opt/majnet
EOF
)

unit() { # unit <name> <extra-unit-lines>
  local name=$1 extra=$2
  cat > "/etc/systemd/system/majnet-$name.service" <<EOF
[Unit]
Description=MajNet $name
After=network-online.target wg-quick@wg0.service
Wants=network-online.target
Requires=wg-quick@wg0.service
$extra
[Service]
EnvironmentFile=$ETC/$name.env
ExecStart=/usr/local/bin/majnet-$name
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF
}
# The bot stays down until the wizard writes its App credentials.
unit bot "ConditionPathExists=$ETC/github-app.pem"
unit reconciler ""
unit setup ""
systemctl daemon-reload
systemctl enable --now majnet-bot majnet-reconciler majnet-setup

log "install complete"
echo
echo "  ┌──────────────────────────────────────────────────────────────┐"
echo "    Open the setup wizard to finish (GitHub App, nodes):"
echo
echo "    http://$PUBLIC_IP:7600/?token=$(cat "$ETC/setup-token")"
echo "  └──────────────────────────────────────────────────────────────┘"
echo
echo "  Prerequisite for the wizard: the root GitHub org must already exist."
echo "  Dashboard (optional, after Tailscale is up): see dashboard/README.md."
