#!/usr/bin/env bash
# MajNet one-line installer — MAIN node only (ADR 0004, roadmap phase 6):
#
#   curl -fsSL https://raw.githubusercontent.com/majnet/majnet/main/bootstrap/install.sh | bash
#
# Bootstraps this node as `main`, builds and installs the control plane
# (bot, reconciler, setup) as systemd services, generates all local key
# material, and prints the setup-wizard URL. Worker nodes are enrolled from
# the wizard — never run this on them. Idempotent; safe to re-run.
#
# Env overrides: MAJNET_REPO_URL, MAJNET_REF, MAJNET_PUBLIC_IP, MAJNET_DOMAIN
# (a DNS name already pointing at this node — enables Caddy TLS, ADR 0006),
# MAJNET_ADMIN_SSH_KEYS (admin authorized_keys; required if root has none —
# hardening disables password + root login, so a key must exist somewhere).

set -euo pipefail

REPO_URL=${MAJNET_REPO_URL:-https://github.com/majnet/majnet}
REF=${MAJNET_REF:-main}
DOMAIN=${MAJNET_DOMAIN:-}
DIR=/opt/majnet
ETC=/etc/majnet

log() { printf '\033[1;34m[majnet-install]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[majnet-install]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root"
[[ -f /etc/debian_version ]] || die "Debian only (design doc §4)"

log "installing runtime dependencies"
apt-get update -q
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  git curl ca-certificates age openssl openssh-client gnupg
# No build toolchain: the control plane is pulled as CI-built images (ADR 0008),
# not compiled here. Only the `bootstrap/` shell + compose payload is checked out.

log "fetching $REPO_URL @ $REF → $DIR"
if [[ -d $DIR/.git ]]; then
  git -C "$DIR" fetch --depth 1 origin "$REF"
  git -C "$DIR" checkout -q FETCH_HEAD
else
  git clone --depth 1 --branch "$REF" "$REPO_URL" "$DIR"
fi

mkdir -p "$ETC"

PUBLIC_IP=${MAJNET_PUBLIC_IP:-$(curl -fsS4 --max-time 10 https://ifconfig.me || true)}
[[ -n $PUBLIC_IP ]] || die "could not detect the public IP — set MAJNET_PUBLIC_IP"

# --- admin SSH keys (anti-lockout) ---------------------------------------
# 10-base disables password + root SSH login, so the majnet admin user's
# authorized_keys are the ONLY way back in. Prefer an explicit override,
# else inherit whatever key got the operator in as root. If both are empty
# (e.g. root was reached by password), refuse — hardening would lock the
# operator out with no key anywhere.
ADMIN_KEYS=${MAJNET_ADMIN_SSH_KEYS:-}
[[ -n $ADMIN_KEYS ]] || ADMIN_KEYS=$(grep -hv '^[[:space:]]*$' /root/.ssh/authorized_keys 2>/dev/null || true)
if [[ ! -f $ETC/node.env && -z ${ADMIN_KEYS//[[:space:]]/} ]]; then
  die "no SSH key found for the admin user — you would be locked out once bootstrap
  disables password and root SSH login. Add your public key to /root/.ssh/authorized_keys
  (then re-run), or re-run with:  MAJNET_ADMIN_SSH_KEYS='ssh-ed25519 AAAA... you' bash"
fi

# --- node.env (role=main) ------------------------------------------------
if [[ ! -f $ETC/node.env ]]; then
  log "writing $ETC/node.env (role=main)"
  (umask 077; cat > "$ETC/node.env" <<EOF
# Generated by install.sh — re-rendered by majnet-setup on node enrollment.
NODE_NAME=main
NODE_ROLE=main
WG_ADDRESS=10.88.0.1/24
WG_LISTEN_PORT=51820
WG_PEERS=""
DOCKER_API_PORT=2376
ADMIN_USER=majnet
ADMIN_SSH_KEYS="
$ADMIN_KEYS
"
BESZEL_HUB_URL=http://10.88.0.1:8090
BESZEL_AGENT_KEY=
RESTIC_REPOSITORY=
EOF
  )
fi
# TLS proxy flag (ADR 0006) — read by the firewall step; also on re-runs
# where node.env predates the domain.
if [[ -n $DOMAIN ]] && ! grep -q '^MAIN_TLS_PROXY=1$' "$ETC/node.env"; then
  echo 'MAIN_TLS_PROXY=1' >> "$ETC/node.env"
fi

# --- key material (before bootstrap: step 30 points dockerd at the certs) -
log "generating key material"
PKI_CA="$ETC/pki-ca"
bash "$DIR/bootstrap/pki/gen-certs.sh" "$PKI_CA" >/dev/null
install -D -m 0600 "$PKI_CA/ca.pem"               "$ETC/pki/ca.pem"
install -D -m 0600 "$PKI_CA/server-main-cert.pem" "$ETC/pki/server-cert.pem"
install -D -m 0600 "$PKI_CA/server-main-key.pem"  "$ETC/pki/server-key.pem"
install -D -m 0600 "$PKI_CA/reconciler-cert.pem"  "$ETC/pki/reconciler-cert.pem"
install -D -m 0600 "$PKI_CA/reconciler-key.pem"   "$ETC/pki/reconciler-key.pem"

install -d -m 0700 "$ETC/age"
[[ -f $ETC/age/age-stable.key     ]] || age-keygen -o "$ETC/age/age-stable.key"     2>/dev/null
[[ -f $ETC/age/age-production.key ]] || age-keygen -o "$ETC/age/age-production.key" 2>/dev/null
[[ -f $ETC/age/db-master.key      ]] || (umask 077; openssl rand -hex 32 > "$ETC/age/db-master.key")

[[ -f $ETC/enroll_ed25519 ]] || ssh-keygen -q -t ed25519 -N '' -C majnet-enroll -f "$ETC/enroll_ed25519"
[[ -f $ETC/setup-token    ]] || (umask 077; openssl rand -hex 24 > "$ETC/setup-token")

# --- bootstrap this node ---------------------------------------------------
log "bootstrapping node 'main' (WireGuard, Docker, firewall)"
bash "$DIR/bootstrap/bootstrap.sh"

# --- TLS proxy (ADR 0006) --------------------------------------------------
# After the firewall step: 80/443 are open, so the ACME challenge can pass.
if [[ -n $DOMAIN ]]; then
  if ! command -v caddy &>/dev/null; then
    log "installing Caddy (ACME TLS for webhooks + wizard)"
    curl -1fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key |
      gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1fsSL https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
      > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -q
    DEBIAN_FRONTEND=noninteractive apt-get install -y caddy
  fi
  log "writing /etc/caddy/Caddyfile for $DOMAIN"
  cat > /etc/caddy/Caddyfile <<EOF
# Managed by majnet install.sh (ADR 0006) — do not edit by hand.
# /webhook + /healthz → bot; everything else → setup wizard. The wizard
# listener closes at /finish; 502 on those paths afterwards is expected.
$DOMAIN {
	handle /webhook* {
		reverse_proxy 127.0.0.1:8080
	}
	handle /healthz {
		reverse_proxy 127.0.0.1:8080
	}
	handle {
		reverse_proxy 127.0.0.1:7600
	}
}
EOF
  systemctl enable --now caddy
  systemctl reload caddy
fi

# --- control plane: pull the CI-built images (ADR 0008) --------------------
# bot + reconciler + dashboard run as compose services from the GHCR image;
# `setup` rides along in the image but runs native (it drives systemctl/wg).
# Nothing compiles here.
CP_IMAGE=${MAJNET_CONTROL_PLANE_IMAGE:-ghcr.io/majnet/majnet/control-plane:latest}
DASH_IMAGE=${MAJNET_DASHBOARD_IMAGE:-ghcr.io/majnet/majnet/dashboard:latest}
log "pulling control-plane images"
docker pull -q "$CP_IMAGE"
docker pull -q "$DASH_IMAGE"
# Extract the native setup binary from the image; install the update script.
cid=$(docker create "$CP_IMAGE")
docker cp "$cid:/usr/local/bin/majnet-setup" /usr/local/bin/majnet-setup
docker rm -f "$cid" >/dev/null
chmod 0755 /usr/local/bin/majnet-setup
install -m 0755 "$DIR/bootstrap/majnet-update" /usr/local/bin/

# --- service config --------------------------------------------------------
# bot.env is written by the wizard (App credentials); reconciler + setup now.
(umask 077; cat > "$ETC/reconciler.env" <<'EOF'
MAJNET_BOT_URL=http://10.88.0.1:8081
MAJNET_LISTEN=10.88.0.1:9090
MAJNET_ROOT_ORG=majksa-platform
MAJNET_AGE_KEY_DIR=/etc/majnet/age
MAJNET_DOCKER_CERT_DIR=/etc/majnet/pki
MAJNET_DATA_DIR=/var/lib/majnet-reconciler
EOF
)
(umask 077; cat > "$ETC/setup.env" <<'EOF'
MAJNET_SETUP_LISTEN_PUBLIC=0.0.0.0:7600
MAJNET_SETUP_LISTEN_INTERNAL=10.88.0.1:7601
MAJNET_BOT_INTERNAL_URL=http://10.88.0.1:8081
MAJNET_ETC_DIR=/etc/majnet
MAJNET_REPO_DIR=/opt/majnet
EOF
)
if [[ -n $DOMAIN ]]; then
  echo "MAJNET_PUBLIC_BASE_URL=https://$DOMAIN" >> "$ETC/setup.env"
fi
# Pinned images for compose (auto-loaded as deploy/.env by every compose call).
printf 'MAJNET_CONTROL_PLANE_IMAGE=%s\nMAJNET_DASHBOARD_IMAGE=%s\n' \
  "$CP_IMAGE" "$DASH_IMAGE" > "$DIR/deploy/.env"

# --- setup service (native) ------------------------------------------------
cat > /etc/systemd/system/majnet-setup.service <<EOF
[Unit]
Description=MajNet setup
After=network-online.target wg-quick@wg0.service
Wants=network-online.target
Requires=wg-quick@wg0.service
[Service]
EnvironmentFile=$ETC/setup.env
ExecStart=/usr/local/bin/majnet-setup
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF

# Self-update: converge the control plane to the version.yaml pin (ADR 0005/0008
# — pulls images, extracts setup; never compiles). Polled every ~30s so a
# dashboard-published pin rolls out within ~1 min; majnet-update is a cheap
# no-op (one curl + a stamp compare) while the pin is unchanged.
cat > /etc/systemd/system/majnet-update.service <<'EOF'
[Unit]
Description=MajNet control-plane update (ADR 0005/0008)
After=network-online.target docker.service
Wants=network-online.target
[Service]
Type=oneshot
ExecStart=/usr/local/bin/majnet-update
EOF
cat > /etc/systemd/system/majnet-update.timer <<'EOF'
[Unit]
Description=MajNet control-plane update check (polls version.yaml)
[Timer]
OnBootSec=30
OnUnitActiveSec=30
RandomizedDelaySec=10
Persistent=true
[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now majnet-setup majnet-update.timer

# Bring up reconciler + dashboard now; the bot follows once the wizard writes
# its App credentials (its env_file is optional so compose parses without it).
log "starting the control-plane compose (reconciler + dashboard)"
docker compose -f "$DIR/deploy/compose.yaml" up -d reconciler dashboard

if [[ -n $DOMAIN ]]; then
  WIZARD_URL="https://$DOMAIN/?token=$(cat "$ETC/setup-token")"
else
  WIZARD_URL="http://$PUBLIC_IP:7600/?token=$(cat "$ETC/setup-token")"
fi
log "install complete"
echo
echo "  ┌──────────────────────────────────────────────────────────────┐"
echo "    Open the setup wizard to finish (GitHub App, nodes):"
echo
echo "    $WIZARD_URL"
echo "  └──────────────────────────────────────────────────────────────┘"
echo
echo "  Prerequisite for the wizard: the root GitHub org must already exist."
echo "  Dashboard: run 'tailscale up', then '$DIR/bootstrap/bootstrap.sh 70'."
